package main;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import utility.Koneksi_db;

/**
 *
 * @author Putra Prasetya
 */
public class Daftar extends javax.swing.JFrame {
    private Connection conn = new Koneksi_db().connect();
    public Daftar() {
        initComponents();
        setSize(750, 450);
        setLocationRelativeTo(null);
        sembunyikan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg11 = new utility.Bg_masuk();
        btn_kembali = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_kode = new javax.swing.JPanel();
        lb_teksKode = new javax.swing.JLabel();
        tf_kodeAktivasi = new javax.swing.JTextField();
        lb_kode = new javax.swing.JLabel();
        btn_cek = new javax.swing.JButton();
        lb_kodeSalah = new javax.swing.JLabel();
        panel_daftar = new javax.swing.JPanel();
        tf_nama = new javax.swing.JTextField();
        cb_sandi = new javax.swing.JCheckBox();
        tf_sandi = new javax.swing.JPasswordField();
        tf_email = new javax.swing.JTextField();
        lb_nama = new javax.swing.JLabel();
        lb_sandi = new javax.swing.JLabel();
        lb_email = new javax.swing.JLabel();
        btn_daftar = new javax.swing.JButton();
        lb_daftarSalah = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 204, 150));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Daftar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 431, 40));

        panel_kode.setBackground(new java.awt.Color(255, 255, 204));

        lb_teksKode.setText("Sebelum daftar admin. Anda perlu mengisi kode aktivasi terlebih dahulu.");

        tf_kodeAktivasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_kodeAktivasiKeyPressed(evt);
            }
        });

        lb_kode.setLabelFor(btn_cek);
        lb_kode.setText("Kode Aktivasi");

        btn_cek.setText("Cek");
        btn_cek.setMaximumSize(new java.awt.Dimension(63, 23));
        btn_cek.setMinimumSize(new java.awt.Dimension(63, 23));
        btn_cek.setPreferredSize(new java.awt.Dimension(63, 23));
        btn_cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cekActionPerformed(evt);
            }
        });

        lb_kodeSalah.setBackground(new java.awt.Color(255, 255, 204, 150));
        lb_kodeSalah.setFont(new java.awt.Font("SansSerif", 2, 11)); // NOI18N
        lb_kodeSalah.setForeground(new java.awt.Color(255, 0, 0));
        lb_kodeSalah.setText("pesan kesalahan");

        javax.swing.GroupLayout panel_kodeLayout = new javax.swing.GroupLayout(panel_kode);
        panel_kode.setLayout(panel_kodeLayout);
        panel_kodeLayout.setHorizontalGroup(
            panel_kodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kodeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_kodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_kodeLayout.createSequentialGroup()
                        .addComponent(lb_teksKode)
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addGroup(panel_kodeLayout.createSequentialGroup()
                        .addComponent(lb_kode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_kodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_kodeLayout.createSequentialGroup()
                                .addComponent(lb_kodeSalah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_cek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_kodeAktivasi))))
                .addContainerGap())
        );
        panel_kodeLayout.setVerticalGroup(
            panel_kodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kodeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_teksKode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_kodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_kodeAktivasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_kode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_kodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_kodeSalah))
                .addGap(16, 16, 16))
        );

        jPanel1.add(panel_kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 430, 90));

        panel_daftar.setBackground(new java.awt.Color(255, 255, 204));

        tf_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_namaKeyPressed(evt);
            }
        });

        cb_sandi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_sandi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb_sandi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cb_sandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sandiActionPerformed(evt);
            }
        });

        tf_sandi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_sandiKeyPressed(evt);
            }
        });

        tf_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_emailKeyPressed(evt);
            }
        });

        lb_nama.setText("Nama");

        lb_sandi.setText("Sandi");

        lb_email.setText("Email");

        btn_daftar.setText("Daftar");
        btn_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftarActionPerformed(evt);
            }
        });

        lb_daftarSalah.setBackground(new java.awt.Color(255, 255, 204, 150));
        lb_daftarSalah.setFont(new java.awt.Font("SansSerif", 2, 11)); // NOI18N
        lb_daftarSalah.setForeground(new java.awt.Color(255, 0, 0));
        lb_daftarSalah.setText("pesan kesalahan");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Lanjutkan Daftar Akun");

        javax.swing.GroupLayout panel_daftarLayout = new javax.swing.GroupLayout(panel_daftar);
        panel_daftar.setLayout(panel_daftarLayout);
        panel_daftarLayout.setHorizontalGroup(
            panel_daftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_daftarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_daftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_nama, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(lb_sandi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_daftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_daftarLayout.createSequentialGroup()
                        .addComponent(lb_daftarSalah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_daftar))
                    .addComponent(tf_nama, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_email, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_daftarLayout.createSequentialGroup()
                        .addComponent(tf_sandi, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_sandi)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panel_daftarLayout.setVerticalGroup(
            panel_daftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_daftarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_daftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nama)
                    .addComponent(lb_nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_daftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_daftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_sandi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cb_sandi, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(lb_sandi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_daftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_daftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_daftar)
                    .addComponent(lb_daftarSalah))
                .addGap(38, 38, 38))
        );

        jPanel1.add(panel_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 430, 170));

        javax.swing.GroupLayout bg11Layout = new javax.swing.GroupLayout(bg11);
        bg11.setLayout(bg11Layout);
        bg11Layout.setHorizontalGroup(
            bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg11Layout.createSequentialGroup()
                .addContainerGap(650, Short.MAX_VALUE)
                .addComponent(btn_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(bg11Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bg11Layout.setVerticalGroup(
            bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_kembali)
                .addGap(95, 95, 95)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void sembunyikan(){
        lb_kodeSalah.setVisible(false);
        lb_daftarSalah.setVisible(false);
        panel_daftar.setVisible(false);
    }
    
    private void errorKedip(JLabel label, String pesan){
        label.setVisible(false);
        Timer timer = new Timer(500, event -> {
                label.setVisible(true);
                label.setText(pesan);
            });
        timer.setRepeats(false);
        timer.start();
    }
    
    private void btn_cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cekActionPerformed
        String kode = tf_kodeAktivasi.getText();
        if (kode.equals("")) errorKedip(lb_kodeSalah,"Kode Kosong !");
        else {
            String sql = "SELECT * FROM aktivasi WHERE kode_aktivasi = '"+kode+"'";
            try {
                Statement stat = conn.createStatement();
                ResultSet hasil = stat.executeQuery(sql);
                if (hasil.next()){
                    int id = hasil.getInt("id_aktivasi");
                    sql = "SELECT * FROM admin WHERE aktivasi_id = '"+id+"'";
                    hasil = stat.executeQuery(sql);
                    if (hasil.next()) errorKedip(lb_kodeSalah,"Kode Sudah Dipakai !");
                    else tampilDaftar();
                } else errorKedip(lb_kodeSalah,"Kode Salah !");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Gagal cek Kode Aktivasi : "+e);
            }
        }   
    }//GEN-LAST:event_btn_cekActionPerformed
    
    private void tampilDaftar(){
        panel_daftar.setVisible(true);
        lb_teksKode.setEnabled(false);
        lb_kode.setEnabled(false);
        tf_kodeAktivasi.setEnabled(false);
        btn_cek.setEnabled(false);                 
        panel_kode.setBackground(new java.awt.Color(211, 212, 171));
        lb_kodeSalah.setVisible(false);
    }
    
    private void btn_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftarActionPerformed
        // Cek: nama, sandi, email kosong & Nama sudah ada
        String nama = tf_nama.getText();
        String sandi = String.valueOf(tf_sandi.getPassword());
        String email = tf_email.getText();
        if (nama.equals("")) errorKedip(lb_daftarSalah,"Nama Kosong !");
        else if (sandi.equals("")) errorKedip(lb_daftarSalah,"Sandi Kosong !");
        else if (email.equals("")) errorKedip(lb_daftarSalah,"Email Kosong !");
        else if (cekNama(nama)) errorKedip(lb_daftarSalah,"Nama Sudah Ada !");
        else {
            // Tambahkan akun baru ke database
            String kodeAktivasi = tf_kodeAktivasi.getText();
            int idAktivasi = ambilId(kodeAktivasi);           
            buatAkun(idAktivasi, nama, sandi, email);
            this.dispose();
        }        
    }//GEN-LAST:event_btn_daftarActionPerformed

    private boolean cekNama(String pnama){
        boolean out = false;
        String nama = "";
        String sql = "SELECT nama_admin FROM admin WHERE nama_admin = '"+pnama+"'";
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            if (hasil.next()){
                nama = hasil.getString("nama_admin");
                if (nama.equals(pnama)) out = true;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal ambil nama : "+e);
        }
        return out;
    }

    private void buatAkun (int pidAktivasi, String pnama, String psandi, String pemail) {
        String sql = "INSERT INTO admin VALUES (?,?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, pnama);
            stat.setInt(2, pidAktivasi);
            stat.setString(3, psandi);
            stat.setString(4, pemail);
            stat.setString(5, "AA");
            stat.setString(6, "ZZZ");
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Akun Berhasil Dibuat !");
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Gagal membuat akun : "+e);
        }
    }
    
    private int ambilId (String pkode){
        int id = 0;
        String sql = "SELECT id_aktivasi FROM aktivasi WHERE kode_aktivasi = '"+pkode+"'";
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            if (hasil.next()){
                id = hasil.getInt("id_aktivasi");
            }            
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Gagal ambil id aktivasi : "+e);
        }
        return id;
    }
    
    private void cb_sandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sandiActionPerformed
        if (cb_sandi.isSelected()){
            tf_sandi.setEchoChar((char)0);
        } else {
            tf_sandi.setEchoChar('*');
        }
    }//GEN-LAST:event_cb_sandiActionPerformed

    private void tf_kodeAktivasiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_kodeAktivasiKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            btn_cek.doClick();
        }
    }//GEN-LAST:event_tf_kodeAktivasiKeyPressed

    private void tf_namaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_namaKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            tf_sandi.requestFocus();
        }
    }//GEN-LAST:event_tf_namaKeyPressed

    private void tf_sandiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_sandiKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            tf_email.requestFocus();
        }
    }//GEN-LAST:event_tf_sandiKeyPressed

    private void tf_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_emailKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            btn_daftar.doClick();
        }
    }//GEN-LAST:event_tf_emailKeyPressed
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utility.Bg_masuk bg11;
    private javax.swing.JButton btn_cek;
    private javax.swing.JButton btn_daftar;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JCheckBox cb_sandi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_daftarSalah;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_kode;
    private javax.swing.JLabel lb_kodeSalah;
    private javax.swing.JLabel lb_nama;
    private javax.swing.JLabel lb_sandi;
    private javax.swing.JLabel lb_teksKode;
    private javax.swing.JPanel panel_daftar;
    private javax.swing.JPanel panel_kode;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_kodeAktivasi;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JPasswordField tf_sandi;
    // End of variables declaration//GEN-END:variables
}
