package main;

import java.awt.Dimension;
import java.awt.Rectangle;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import utility.Koneksi_db;

/**
 * @author Putra Prasetya
 */
public class Laporan extends javax.swing.JFrame {
    private Connection conn = new Koneksi_db().connect();
    private String judul ="", alamat="", telp="", hrd="", purchasing="", sales="", stock="";
    
    public Laporan() {
        initComponents();
        rb_tampil_semua.setSelected(true);
        Locale locale = new Locale ("id","ID");
        Locale.setDefault(locale);
        dapatkanTemplatLaporan();
    }
    
    public Laporan(Rectangle bound) {
        initComponents();
        rb_tampil_semua.setSelected(true);
        Locale locale = new Locale ("id","ID");
        Locale.setDefault(locale);
        dapatkanTemplatLaporan();
        
        // terima ukuran window & tetapkan di window yang aktif
        this.setBounds(bound);
               
        //saat restore dari kondisi maximize kembali ke ukuran minimal
        Dimension size = this.getSize();
        Double width = size.getWidth();
        Double height = size.getHeight();
        if (width > 1381 && height > 743) {
            this.setSize(800,500);
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rb_group_tampil = new javax.swing.ButtonGroup();
        bg21 = new utility.bg2();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        btn_pegawai = new javax.swing.JButton();
        btn_pemasok = new javax.swing.JButton();
        btn_pembelian = new javax.swing.JButton();
        btn_barang = new javax.swing.JButton();
        dt_dari_pembelian = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dt_sampai_pembelian = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        dt_dari_barang = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        dt_sampai_barang = new com.toedter.calendar.JDateChooser();
        jLabel45 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dt_dari_penjualan = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        dt_sampai_penjualan = new com.toedter.calendar.JDateChooser();
        btn_penjualan = new javax.swing.JButton();
        dt_dari_penyesuaian = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        dt_sampai_penyesuaian = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        btn_penyesuaian = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rb_tampil_semua = new javax.swing.JRadioButton();
        rb_tampil_belum = new javax.swing.JRadioButton();
        rb_tampil_beres = new javax.swing.JRadioButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dt_dari_pembelian_detail = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        dt_sampai_pembelian_detail = new com.toedter.calendar.JDateChooser();
        btn_pembelian_detail = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dt_dari_penjualan_detail = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        dt_sampai_penjualan_detail = new com.toedter.calendar.JDateChooser();
        btn_penjualan_detail = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        btn_templat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Laporan Pegawai-------------");

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Laporan Pemasok------------");

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Laporan Pembelian----------");

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Laporan Barang---------------");

        btn_pegawai.setText("Cetak");
        btn_pegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pegawaiActionPerformed(evt);
            }
        });

        btn_pemasok.setText("Cetak");
        btn_pemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pemasokActionPerformed(evt);
            }
        });

        btn_pembelian.setText("Cetak");
        btn_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pembelianActionPerformed(evt);
            }
        });

        btn_barang.setText("Cetak");
        btn_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_barangActionPerformed(evt);
            }
        });

        dt_dari_pembelian.setPreferredSize(new java.awt.Dimension(105, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dari :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Sampai :");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dari :");

        dt_dari_barang.setPreferredSize(new java.awt.Dimension(105, 20));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Sampai :");

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Laporan Penjualan-----------");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Dari :");

        dt_dari_penjualan.setPreferredSize(new java.awt.Dimension(105, 20));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" Sampai :");

        btn_penjualan.setText("Cetak");
        btn_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_penjualanActionPerformed(evt);
            }
        });

        dt_dari_penyesuaian.setPreferredSize(new java.awt.Dimension(105, 20));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Dari :");

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Laporan Penyesuaian-------");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" Sampai :");

        btn_penyesuaian.setText("Cetak");
        btn_penyesuaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_penyesuaianActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tampilkan :");

        rb_group_tampil.add(rb_tampil_semua);
        rb_tampil_semua.setForeground(new java.awt.Color(255, 255, 255));
        rb_tampil_semua.setText("Semua");

        rb_group_tampil.add(rb_tampil_belum);
        rb_tampil_belum.setForeground(new java.awt.Color(255, 255, 255));
        rb_tampil_belum.setText("Belum Sesuai");

        rb_group_tampil.add(rb_tampil_beres);
        rb_tampil_beres.setForeground(new java.awt.Color(255, 255, 255));
        rb_tampil_beres.setText("Beres");

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Laporan Pembelian Detail--");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dari :");

        dt_dari_pembelian_detail.setPreferredSize(new java.awt.Dimension(105, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" Sampai :");

        btn_pembelian_detail.setText("Cetak");
        btn_pembelian_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pembelian_detailActionPerformed(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Laporan Penjualan Detail---");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Dari :");

        dt_dari_penjualan_detail.setPreferredSize(new java.awt.Dimension(105, 20));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(" Sampai :");

        btn_penjualan_detail.setText("Cetak");
        btn_penjualan_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_penjualan_detailActionPerformed(evt);
            }
        });

        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Laporan");

        btn_templat.setText("Templat Laporan");
        btn_templat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_templatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg21Layout = new javax.swing.GroupLayout(bg21);
        bg21.setLayout(bg21Layout);
        bg21Layout.setHorizontalGroup(
            bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg21Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dt_dari_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dt_sampai_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dt_dari_pembelian_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dt_sampai_pembelian_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_pembelian_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg21Layout.createSequentialGroup()
                            .addComponent(btn_kembali)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rb_tampil_semua)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rb_tampil_belum)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rb_tampil_beres)
                            .addGap(18, 18, 18)
                            .addComponent(btn_penyesuaian, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bg21Layout.createSequentialGroup()
                                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(bg21Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dt_dari_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dt_sampai_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bg21Layout.createSequentialGroup()
                                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btn_pegawai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_pemasok, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_templat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bg21Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dt_dari_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dt_sampai_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bg21Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dt_dari_penyesuaian, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dt_sampai_penyesuaian, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(90, 90, 90))
                                    .addGroup(bg21Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dt_dari_penjualan_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dt_sampai_penjualan_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_penjualan_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel23))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        bg21Layout.setVerticalGroup(
            bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg21Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pegawai)
                    .addComponent(btn_templat))
                .addGap(18, 18, 18)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pemasok))
                .addGap(18, 18, 18)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_pembelian))
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dt_dari_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt_sampai_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_pembelian_detail))
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dt_dari_pembelian_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt_sampai_pembelian_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_barang))
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dt_dari_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt_sampai_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_penjualan))
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dt_dari_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt_sampai_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_penjualan_detail)
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dt_dari_penjualan_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt_sampai_penjualan_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dt_dari_penyesuaian, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt_sampai_penyesuaian, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_tampil_semua)
                            .addComponent(rb_tampil_belum)
                            .addComponent(rb_tampil_beres)
                            .addComponent(btn_penyesuaian)))
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btn_kembali)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesanPopUp(String pesan){
        JOptionPane.showMessageDialog(null, pesan);
    }
    
    private void pesanSQLPopUp(String pesan, SQLException ee){
        JOptionPane.showMessageDialog(null, pesan+" : "+ee);
    } 
    
    private String ambilPathLogo(){
        return System.getProperty("user.dir")+"\\src\\img\\logo_60px.png";
    }
    
    private void btn_pegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pegawaiActionPerformed
        try {
            String namaFile = "src/reports/pegawai.jasper";
            Connection conn = new Koneksi_db().connect();
            Map<String, Object> parameter = new HashMap<>();
            parameter.put("PARA_JUDUL", judul);
            parameter.put("PARA_ALAMAT", alamat);
            parameter.put("PARA_TELP", telp);
            parameter.put("PARA_HRD", hrd);
            parameter.put("PARA_LOGO", ambilPathLogo());
            File report_file = new File(namaFile);
            
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
            JasperViewer.viewReport(jasperPrint, false); 
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (JRException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btn_pegawaiActionPerformed

    private void btn_pemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pemasokActionPerformed
        try{
            String namaFile = "src/reports/pemasok.jasper";
            Connection conn = new Koneksi_db().connect();
            Map<String, Object> parameter = new HashMap<>();
            parameter.put("PARA_JUDUL", judul);
            parameter.put("PARA_ALAMAT", alamat);
            parameter.put("PARA_TELP", telp);
            parameter.put("PARA_PURCHASING", purchasing);
            parameter.put("PARA_LOGO", ambilPathLogo());
            File report_file = new File (namaFile);
            
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
            JasperViewer.viewReport(jasperPrint, false); 
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (JRException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btn_pemasokActionPerformed

    private void btn_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pembelianActionPerformed
        Date dari_pembelian = (Date) dt_dari_pembelian.getDate();
        Date sampai_pembelian = (Date) dt_sampai_pembelian.getDate();
        
        if (dari_pembelian==null) pesanPopUp("Tanggal pembelian 'Dari' belum diisi !");
        else if (sampai_pembelian==null) pesanPopUp("Tanggal pembelian 'Sampai' belum diisi ! ");
        else {
            SimpleDateFormat Format_English = new SimpleDateFormat("yyyy-MM-dd");            
            String dari_english = Format_English.format(dari_pembelian);        
            String sampai_english = Format_English.format(sampai_pembelian);
            
            SimpleDateFormat Format_Indo = new SimpleDateFormat("dd-MM-yyyy");
            String dari_indo = Format_Indo.format(dari_pembelian);        
            String sampai_indo = Format_Indo.format(sampai_pembelian);
            
            try {
                String namaFile = "src/reports/pembelian.jasper";                
                Map<String, Object> parameter = new HashMap<>();
                parameter.put("PARA_DARI_INDO", dari_indo);
                parameter.put("PARA_SAMPAI_INDO", sampai_indo);
                parameter.put("PARA_DARI_ENGLISH", dari_english);
                parameter.put("PARA_SAMPAI_ENGLISH", sampai_english);
                parameter.put("PARA_JUDUL", judul);
                parameter.put("PARA_ALAMAT", alamat);
                parameter.put("PARA_TELP", telp);
                parameter.put("PARA_PURCHASING", purchasing);
                parameter.put("PARA_LOGO", ambilPathLogo());
                File report_file = new File (namaFile);
            
                JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
                JasperViewer.viewReport(jasperPrint, false); 
                JasperViewer.setDefaultLookAndFeelDecorated(true);
            } catch (JRException e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }            
        }
    }//GEN-LAST:event_btn_pembelianActionPerformed

    private void btn_pembelian_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pembelian_detailActionPerformed
        Date dari_pembelian = (Date) dt_dari_pembelian_detail.getDate();
        Date sampai_pembelian = (Date) dt_sampai_pembelian_detail.getDate();
        
        if (dari_pembelian==null) pesanPopUp("Tanggal pembelian detail 'Dari' belum diisi !");
        else if (sampai_pembelian==null) pesanPopUp("Tanggal pembelian detail 'Sampai' belum diisi !");
        else {
            SimpleDateFormat Format_English = new SimpleDateFormat("yyyy-MM-dd");            
            String dari_english = Format_English.format(dari_pembelian);        
            String sampai_english = Format_English.format(sampai_pembelian);
            
            SimpleDateFormat Format_Indo = new SimpleDateFormat("dd-MM-yyyy");
            String dari_indo = Format_Indo.format(dari_pembelian);        
            String sampai_indo = Format_Indo.format(sampai_pembelian);
            
            try {
                String namaFile = "src/reports/pembelian_detail.jasper";                
                Map<String, Object> parameter = new HashMap<>();
                parameter.put("PARA_DARI_INDO", dari_indo);
                parameter.put("PARA_SAMPAI_INDO", sampai_indo);
                parameter.put("PARA_DARI_ENGLISH", dari_english);
                parameter.put("PARA_SAMPAI_ENGLISH", sampai_english);
                parameter.put("PARA_JUDUL", judul);
                parameter.put("PARA_ALAMAT", alamat);
                parameter.put("PARA_TELP", telp);
                parameter.put("PARA_PURCHASING", purchasing);
                parameter.put("PARA_LOGO", ambilPathLogo());
                File report_file = new File (namaFile);
            
                JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
                JasperViewer.viewReport(jasperPrint, false); 
                JasperViewer.setDefaultLookAndFeelDecorated(true);
            } catch (JRException e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }            
        }
    }//GEN-LAST:event_btn_pembelian_detailActionPerformed

    private void btn_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_barangActionPerformed
        Date dari_pembelian = (Date) dt_dari_barang.getDate();
        Date sampai_pembelian = (Date) dt_sampai_barang.getDate();
        
        if (dari_pembelian==null) pesanPopUp("Tanggal barang 'Dari' belum diisi !"); 
        else if (sampai_pembelian==null) pesanPopUp("Tanggal barang 'Sampai' belum diisi !");
        else {
            SimpleDateFormat Format_English = new SimpleDateFormat("yyyy-MM-dd");            
            String dari_english = Format_English.format(dari_pembelian);        
            String sampai_english = Format_English.format(sampai_pembelian);
            
            SimpleDateFormat Format_Indo = new SimpleDateFormat("dd-MM-yyyy");
            String dari_indo = Format_Indo.format(dari_pembelian);        
            String sampai_indo = Format_Indo.format(sampai_pembelian);
            
            try {
                String namaFile = "src/reports/barang.jasper";                
                Map<String, Object> parameter = new HashMap<>();
                parameter.put("PARA_DARI_INDO", dari_indo);
                parameter.put("PARA_SAMPAI_INDO", sampai_indo);
                parameter.put("PARA_DARI_ENGLISH", dari_english);
                parameter.put("PARA_SAMPAI_ENGLISH", sampai_english);
                parameter.put("PARA_JUDUL", judul);
                parameter.put("PARA_ALAMAT", alamat);
                parameter.put("PARA_TELP", telp);
                parameter.put("PARA_PURCHASING", purchasing);
                parameter.put("PARA_LOGO", ambilPathLogo());
                File report_file = new File (namaFile);
            
                JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
                JasperViewer.viewReport(jasperPrint, false); 
                JasperViewer.setDefaultLookAndFeelDecorated(true);
            } catch (JRException e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }            
        }
    }//GEN-LAST:event_btn_barangActionPerformed

    private void btn_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_penjualanActionPerformed
        Date dari_pembelian = (Date) dt_dari_penjualan.getDate();
        Date sampai_pembelian = (Date) dt_sampai_penjualan.getDate();
        
        if(dari_pembelian==null) pesanPopUp("Tanggal penjualan 'Dari' belum diisi !");
        else if (sampai_pembelian==null) pesanPopUp("Tanggal penjualan 'Sampai' belum diisi !");
        else {
            SimpleDateFormat Format_English = new SimpleDateFormat("yyyy-MM-dd");            
            String dari_english = Format_English.format(dari_pembelian);        
            String sampai_english = Format_English.format(sampai_pembelian);
            
            SimpleDateFormat Format_Indo = new SimpleDateFormat("dd-MM-yyyy");
            String dari_indo = Format_Indo.format(dari_pembelian);        
            String sampai_indo = Format_Indo.format(sampai_pembelian);
            
            try {
                String namaFile = "src/reports/penjualan.jasper";                
                Map<String, Object> parameter = new HashMap<>();
                parameter.put("PARA_DARI_INDO", dari_indo);
                parameter.put("PARA_SAMPAI_INDO", sampai_indo);
                parameter.put("PARA_DARI_ENGLISH", dari_english);
                parameter.put("PARA_SAMPAI_ENGLISH", sampai_english);
                parameter.put("PARA_JUDUL", judul);
                parameter.put("PARA_ALAMAT", alamat);
                parameter.put("PARA_TELP", telp);
                parameter.put("PARA_SALES", sales);
                parameter.put("PARA_LOGO", ambilPathLogo());
                File report_file = new File (namaFile);
            
                JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
                JasperViewer.viewReport(jasperPrint, false); 
                JasperViewer.setDefaultLookAndFeelDecorated(true);
            } catch (JRException e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }            
        }
    }//GEN-LAST:event_btn_penjualanActionPerformed

    private void btn_penjualan_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_penjualan_detailActionPerformed
        Date dari_pembelian = (Date) dt_dari_penjualan_detail.getDate();
        Date sampai_pembelian = (Date) dt_sampai_penjualan_detail.getDate();
        
        if (dari_pembelian==null) pesanPopUp("Tanggal penjualan detail 'Dari' belum diisi !");
        else if (sampai_pembelian==null) pesanPopUp("Tanggal penjualan detail 'Sampai' belum diisi !");
        else {
            SimpleDateFormat Format_English = new SimpleDateFormat("yyyy-MM-dd");            
            String dari_english = Format_English.format(dari_pembelian);        
            String sampai_english = Format_English.format(sampai_pembelian);
            
            SimpleDateFormat Format_Indo = new SimpleDateFormat("dd-MM-yyyy");
            String dari_indo = Format_Indo.format(dari_pembelian);        
            String sampai_indo = Format_Indo.format(sampai_pembelian);
            
            try {
                String namaFile = "src/reports/penjualan_detail.jasper";                
                Map<String, Object> parameter = new HashMap<>();
                parameter.put("PARA_DARI_INDO", dari_indo);
                parameter.put("PARA_SAMPAI_INDO", sampai_indo);
                parameter.put("PARA_DARI_ENGLISH", dari_english);
                parameter.put("PARA_SAMPAI_ENGLISH", sampai_english);
                parameter.put("PARA_JUDUL", judul);
                parameter.put("PARA_ALAMAT", alamat);
                parameter.put("PARA_TELP", telp);
                parameter.put("PARA_SALES", sales);
                parameter.put("PARA_LOGO", ambilPathLogo());
                File report_file = new File (namaFile);
            
                JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
                JasperViewer.viewReport(jasperPrint, false); 
                JasperViewer.setDefaultLookAndFeelDecorated(true);
            } catch (JRException e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }            
        }
    }//GEN-LAST:event_btn_penjualan_detailActionPerformed

    private void btn_penyesuaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_penyesuaianActionPerformed
        String status="", status2="";        
        if (rb_tampil_belum.isSelected()) status = "Belum Sesuai";
        else if (rb_tampil_beres.isSelected()) status = "Beres";
        else {
            status = "Belum Sesuai";
            status2 = "Beres";
        }
        
        Date dari_penyesuaian = (Date) dt_dari_penyesuaian.getDate();
        Date sampai_penyesuaian = (Date) dt_sampai_penyesuaian.getDate();
        
        if (dari_penyesuaian==null) pesanPopUp("Tanggal penyesuaian 'Dari' belum diisi !");
        else if (sampai_penyesuaian==null) pesanPopUp("Tanggal penyesuaian 'Sampai' belum diisi !");
        else {
            SimpleDateFormat Format_English = new SimpleDateFormat("yyyy-MM-dd");            
            String dari_english = Format_English.format(dari_penyesuaian);        
            String sampai_english = Format_English.format(sampai_penyesuaian);
            
            SimpleDateFormat Format_Indo = new SimpleDateFormat("dd-MM-yyyy");
            String dari_indo = Format_Indo.format(dari_penyesuaian);        
            String sampai_indo = Format_Indo.format(sampai_penyesuaian);
            
            try {
                String namaFile = "src/reports/penyesuaian.jasper";                
                Map<String, Object> parameter = new HashMap<>();
                parameter.put("PARA_DARI_INDO", dari_indo);
                parameter.put("PARA_SAMPAI_INDO", sampai_indo);
                parameter.put("PARA_DARI_ENGLISH", dari_english);
                parameter.put("PARA_SAMPAI_ENGLISH", sampai_english);
                parameter.put("PARA_STATUS",status);
                parameter.put("PARA_STATUS2", status2);
                parameter.put("PARA_JUDUL", judul);
                parameter.put("PARA_ALAMAT", alamat);
                parameter.put("PARA_TELP", telp);
                parameter.put("PARA_STOCK", stock);
                parameter.put("PARA_LOGO", ambilPathLogo());
                File report_file = new File (namaFile);
            
                JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
                JasperViewer.viewReport(jasperPrint, false); 
                JasperViewer.setDefaultLookAndFeelDecorated(true);
            } catch (JRException e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }            
        }
    }//GEN-LAST:event_btn_penyesuaianActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        Rectangle bound = this.getBounds();
        new Menu(bound).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void dapatkanTemplatLaporan(){
        String query = "SELECT * FROM laporan";
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(query);
            if (hasil.next()){                
                this.judul = hasil.getString("judul_lap");                
                this.alamat = hasil.getString("alamat_lap");
                this.telp = hasil.getString("telp_lap");
                this.hrd = hasil.getString("hrd_lap");
                this.purchasing = hasil.getString("purchasing_lap");
                this.sales = hasil.getString("sales_lap");
                this.stock = hasil.getString("stock_lap");
            }            
        } catch (SQLException e) {
            pesanSQLPopUp("Gagal mengambil data templat laporan",e);
        }
    }
    
    private void btn_templatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_templatActionPerformed
        JTextField tf_judul = new JTextField();
        JTextField tf_alamat = new JTextField();
        JTextField tf_telp = new JTextField();            
        JTextField tf_hrd = new JTextField();
        JTextField tf_purchasing = new JTextField();
        JTextField tf_sales = new JTextField();
        JTextField tf_stock = new JTextField();
        
        tf_judul.setText(judul);
        tf_alamat.setText(alamat);
        tf_telp.setText(telp);
        tf_hrd.setText(hrd);
        tf_purchasing.setText(purchasing);
        tf_sales.setText(sales);
        tf_stock.setText(stock);

        Object[] fields = {
            "KOP Surat ----------------------",
            "Judul :", tf_judul,
            "Alamat :", tf_alamat,
            "Telp :", tf_telp,
            "Nama Pegawai -------------------",
            "HRD :", tf_hrd, 
            "Purchasing Staff :", tf_purchasing,
            "Sales Staff :", tf_sales,
            "Stock Keeper :", tf_stock
        };
        int ok = JOptionPane.showConfirmDialog(null, fields, "Ubah Templat Laporan",
                     JOptionPane.OK_CANCEL_OPTION);
        if (ok==0){
            try {
                String sql = "UPDATE laporan SET judul_lap=?, alamat_lap=?, telp_lap=?, "
                            + "hrd_lap=?, purchasing_lap=?, sales_lap=?, stock_lap=? "
                            + "WHERE id_lap=?";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, tf_judul.getText());
                stat.setString(2, tf_alamat.getText());
                stat.setString(3, tf_telp.getText());
                stat.setString(4, tf_hrd.getText());
                stat.setString(5, tf_purchasing.getText());
                stat.setString(6, tf_sales.getText());
                stat.setString(7, tf_stock.getText());
                stat.setString(8, "1");
                stat.executeUpdate();
            } catch (SQLException e){
                pesanSQLPopUp("Gagal perbarui data templat laporan",e);
            }
            dapatkanTemplatLaporan();
        }
    }//GEN-LAST:event_btn_templatActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
                

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utility.bg2 bg21;
    private javax.swing.JButton btn_barang;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_pegawai;
    private javax.swing.JButton btn_pemasok;
    private javax.swing.JButton btn_pembelian;
    private javax.swing.JButton btn_pembelian_detail;
    private javax.swing.JButton btn_penjualan;
    private javax.swing.JButton btn_penjualan_detail;
    private javax.swing.JButton btn_penyesuaian;
    private javax.swing.JButton btn_templat;
    private com.toedter.calendar.JDateChooser dt_dari_barang;
    private com.toedter.calendar.JDateChooser dt_dari_pembelian;
    private com.toedter.calendar.JDateChooser dt_dari_pembelian_detail;
    private com.toedter.calendar.JDateChooser dt_dari_penjualan;
    private com.toedter.calendar.JDateChooser dt_dari_penjualan_detail;
    private com.toedter.calendar.JDateChooser dt_dari_penyesuaian;
    private com.toedter.calendar.JDateChooser dt_sampai_barang;
    private com.toedter.calendar.JDateChooser dt_sampai_pembelian;
    private com.toedter.calendar.JDateChooser dt_sampai_pembelian_detail;
    private com.toedter.calendar.JDateChooser dt_sampai_penjualan;
    private com.toedter.calendar.JDateChooser dt_sampai_penjualan_detail;
    private com.toedter.calendar.JDateChooser dt_sampai_penyesuaian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.ButtonGroup rb_group_tampil;
    private javax.swing.JRadioButton rb_tampil_belum;
    private javax.swing.JRadioButton rb_tampil_beres;
    private javax.swing.JRadioButton rb_tampil_semua;
    // End of variables declaration//GEN-END:variables
}
