package main;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import utility.Koneksi_db;

/**
 *
 * @author Putra Prasetya
 */
public class LupaSandi extends javax.swing.JFrame {
    private Connection conn = new Koneksi_db().connect();
    public LupaSandi() {
        initComponents();
        setSize(750, 450);
        setLocationRelativeTo(null);
        sembunyikanElemen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg11 = new utility.Bg_masuk();
        btn_kembali = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_nama = new javax.swing.JPanel();
        tf_nama = new javax.swing.JTextField();
        lb_nama = new javax.swing.JLabel();
        btn_cekNama = new javax.swing.JButton();
        lb_salahNama = new javax.swing.JLabel();
        lb_benarNama = new javax.swing.JLabel();
        panel_email = new javax.swing.JPanel();
        lb_email = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        btn_okEmail = new javax.swing.JButton();
        lb_salahEmail = new javax.swing.JLabel();
        lb_benarEmail = new javax.swing.JLabel();
        panel_sandi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_simpanSandi = new javax.swing.JButton();
        lb_salahSandi = new javax.swing.JLabel();
        tf_sandiBaru = new javax.swing.JPasswordField();
        cb_sandi = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        tf_konfirSandi = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 204, 150));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lupa Sandi");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 431, 40));

        panel_nama.setBackground(new java.awt.Color(255, 255, 204));

        tf_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_namaKeyPressed(evt);
            }
        });

        lb_nama.setLabelFor(btn_cekNama);
        lb_nama.setText("Nama");

        btn_cekNama.setText("Cek");
        btn_cekNama.setMaximumSize(new java.awt.Dimension(63, 23));
        btn_cekNama.setMinimumSize(new java.awt.Dimension(63, 23));
        btn_cekNama.setPreferredSize(new java.awt.Dimension(63, 23));
        btn_cekNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cekNamaActionPerformed(evt);
            }
        });

        lb_salahNama.setFont(new java.awt.Font("SansSerif", 2, 11)); // NOI18N
        lb_salahNama.setForeground(new java.awt.Color(255, 0, 0));
        lb_salahNama.setText("pesan kesalahan");

        lb_benarNama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_benarNama.setForeground(new java.awt.Color(204, 255, 204));
        lb_benarNama.setText("Benar !");

        javax.swing.GroupLayout panel_namaLayout = new javax.swing.GroupLayout(panel_nama);
        panel_nama.setLayout(panel_namaLayout);
        panel_namaLayout.setHorizontalGroup(
            panel_namaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_namaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(panel_namaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_namaLayout.createSequentialGroup()
                        .addComponent(lb_salahNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_benarNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cekNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tf_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panel_namaLayout.setVerticalGroup(
            panel_namaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_namaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panel_namaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_nama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_namaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_salahNama)
                    .addComponent(btn_cekNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_benarNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        jPanel1.add(panel_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 430, 75));

        panel_email.setBackground(new java.awt.Color(255, 255, 204));

        lb_email.setText("Email");

        tf_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_emailKeyPressed(evt);
            }
        });

        btn_okEmail.setText("OK");
        btn_okEmail.setMaximumSize(new java.awt.Dimension(63, 23));
        btn_okEmail.setMinimumSize(new java.awt.Dimension(63, 23));
        btn_okEmail.setPreferredSize(new java.awt.Dimension(63, 23));
        btn_okEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okEmailActionPerformed(evt);
            }
        });

        lb_salahEmail.setFont(new java.awt.Font("SansSerif", 2, 11)); // NOI18N
        lb_salahEmail.setForeground(new java.awt.Color(255, 0, 0));
        lb_salahEmail.setText("pesan kesalahan");

        lb_benarEmail.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lb_benarEmail.setForeground(new java.awt.Color(204, 255, 204));
        lb_benarEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_benarEmail.setText("Sukses !");

        javax.swing.GroupLayout panel_emailLayout = new javax.swing.GroupLayout(panel_email);
        panel_email.setLayout(panel_emailLayout);
        panel_emailLayout.setHorizontalGroup(
            panel_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_emailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_emailLayout.createSequentialGroup()
                        .addComponent(lb_salahEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(lb_benarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(btn_okEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tf_email))
                .addContainerGap())
        );
        panel_emailLayout.setVerticalGroup(
            panel_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_emailLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panel_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_email)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_okEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_salahEmail)
                    .addComponent(lb_benarEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        jPanel1.add(panel_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, 430, 75));

        panel_sandi.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setText("Sandi Baru");

        btn_simpanSandi.setText("Simpan");
        btn_simpanSandi.setMaximumSize(new java.awt.Dimension(63, 23));
        btn_simpanSandi.setMinimumSize(new java.awt.Dimension(63, 23));
        btn_simpanSandi.setPreferredSize(new java.awt.Dimension(63, 23));
        btn_simpanSandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanSandiActionPerformed(evt);
            }
        });

        lb_salahSandi.setFont(new java.awt.Font("SansSerif", 2, 11)); // NOI18N
        lb_salahSandi.setForeground(new java.awt.Color(255, 0, 0));
        lb_salahSandi.setText("pesan kesalahan");

        tf_sandiBaru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_sandiBaruKeyPressed(evt);
            }
        });

        cb_sandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sandiActionPerformed(evt);
            }
        });

        jLabel6.setText("Konfirmasi Sandi");

        tf_konfirSandi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_konfirSandiKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panel_sandiLayout = new javax.swing.GroupLayout(panel_sandi);
        panel_sandi.setLayout(panel_sandiLayout);
        panel_sandiLayout.setHorizontalGroup(
            panel_sandiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_sandiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_sandiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_sandiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_sandiLayout.createSequentialGroup()
                        .addComponent(lb_salahSandi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_simpanSandi, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_sandiLayout.createSequentialGroup()
                        .addGroup(panel_sandiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_sandiLayout.createSequentialGroup()
                                .addComponent(tf_sandiBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_sandi))
                            .addComponent(tf_konfirSandi, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_sandiLayout.setVerticalGroup(
            panel_sandiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_sandiLayout.createSequentialGroup()
                .addGroup(panel_sandiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_sandiLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panel_sandiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_sandiBaru, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_sandiLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cb_sandi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(6, 6, 6)
                .addGroup(panel_sandiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_konfirSandi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_sandiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_salahSandi)
                    .addComponent(btn_simpanSandi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel1.add(panel_sandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 430, 110));

        javax.swing.GroupLayout bg11Layout = new javax.swing.GroupLayout(bg11);
        bg11.setLayout(bg11Layout);
        bg11Layout.setHorizontalGroup(
            bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg11Layout.createSequentialGroup()
                .addContainerGap(650, Short.MAX_VALUE)
                .addComponent(btn_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(bg11Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bg11Layout.setVerticalGroup(
            bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_kembali)
                .addGap(95, 95, 95)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void sembunyikanElemen(){
        lb_salahNama.setVisible(false);
        lb_salahEmail.setVisible(false);
        lb_salahSandi.setVisible(false);
        panel_email.setVisible(false);
        panel_sandi.setVisible(false);        
        lb_benarNama.setVisible(false);
        lb_benarEmail.setVisible(false);        
    }
    
    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed
    
    private void btn_cekNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cekNamaActionPerformed
        String nama = tf_nama.getText();
        if (nama.equals("")) errorKedip(lb_salahNama, "Nama Kosong !");
        else {
            boolean namaAda = cekNama(nama);
            if (namaAda) {
                lb_salahNama.setVisible(false);
                lb_benarNama.setVisible(true);
                panel_email.setVisible(true);
                panel_nama.setBackground(new java.awt.Color(211,212,171));
                tf_nama.setEnabled(false);
                btn_cekNama.setEnabled(false);
                lb_nama.setEnabled(false);
            } else errorKedip(lb_salahNama, "Nama Salah !");
        }        
    }//GEN-LAST:event_btn_cekNamaActionPerformed

    private void errorKedip(JLabel label, String pesan){
        label.setVisible(false);
        Timer timer = new Timer(500, event -> {
                label.setVisible(true);
                label.setText(pesan);
            });
        timer.setRepeats(false);
        timer.start();
    }
    
    private boolean cekNama(String pnama) {
        String sql = "SELECT nama_admin FROM admin WHERE nama_admin = '"+pnama+"'";
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            if (hasil.next())return true;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal ambil nama admin : "+e);
        }
        return false;
    }
    
    private void btn_okEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okEmailActionPerformed
        String nama = tf_nama.getText();
        String email = tf_email.getText();
        if (email.equals("")) errorKedip(lb_salahEmail, "Email Kosong !");
        else {
            boolean emailBenar = cekEmail(nama, email);
            if (emailBenar){
                lb_salahEmail.setVisible(false);
                lb_benarEmail.setVisible(true);
                panel_sandi.setVisible(true);
                panel_email.setBackground(new java.awt.Color(211,212,171));
                tf_email.setEnabled(false);
                btn_okEmail.setEnabled(false);
                lb_email.setEnabled(false);
            } else errorKedip(lb_salahEmail, "Email Salah !");
        }
    }//GEN-LAST:event_btn_okEmailActionPerformed

    private boolean cekEmail (String pnama, String pemail){
        String sql = "SELECT * FROM admin WHERE "
                   + "nama_admin = '"+pnama+"' AND email_admin = '"+pemail+"'";
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            if (hasil.next()) return true;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal Cek email: "+e);
        }
        return false;
    }
    
    private void tf_namaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_namaKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            btn_cekNama.doClick();
        }
    }//GEN-LAST:event_tf_namaKeyPressed

    private void tf_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_emailKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            btn_okEmail.doClick();
        }
    }//GEN-LAST:event_tf_emailKeyPressed

    private void tf_sandiBaruKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_sandiBaruKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            tf_konfirSandi.requestFocus();
        }
    }//GEN-LAST:event_tf_sandiBaruKeyPressed

    private void tf_konfirSandiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_konfirSandiKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            btn_simpanSandi.doClick();
        }
    }//GEN-LAST:event_tf_konfirSandiKeyPressed

    private void cb_sandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sandiActionPerformed
        if (cb_sandi.isSelected()){
            tf_sandiBaru.setEchoChar((char)0);
        } else {
            tf_sandiBaru.setEchoChar('*');
        }
    }//GEN-LAST:event_cb_sandiActionPerformed

    private void btn_simpanSandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanSandiActionPerformed
        String sandiBaru = String.valueOf(tf_sandiBaru.getPassword());
        String konfirSandi = String.valueOf(tf_konfirSandi.getPassword());   
        if (sandiBaru.equals("")) errorKedip(lb_salahSandi, "Sandi Baru Kosong !");
        else if (konfirSandi.equals("")) errorKedip(lb_salahSandi, "Konfirmasi Sandi Kosong !");
        else if (!(sandiBaru.equals(konfirSandi))) errorKedip(lb_salahSandi, "Sandi Baru dan Konfirmasi Sandi tidak cocok !");
        else {
            String nama = tf_nama.getText();
            ubahSandi(sandiBaru, nama);
            this.dispose();
        }
    }//GEN-LAST:event_btn_simpanSandiActionPerformed

    private void ubahSandi(String psandiBaru, String pnama){
        String sql = "UPDATE admin SET sandi_admin=? WHERE nama_admin=?";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, psandiBaru);
            stat.setString(2, pnama);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Sandi Berhasil Diubah !");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal Ubah Sandi");
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LupaSandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LupaSandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LupaSandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LupaSandi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LupaSandi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utility.Bg_masuk bg11;
    private javax.swing.JButton btn_cekNama;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_okEmail;
    private javax.swing.JButton btn_simpanSandi;
    private javax.swing.JCheckBox cb_sandi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_benarEmail;
    private javax.swing.JLabel lb_benarNama;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_nama;
    private javax.swing.JLabel lb_salahEmail;
    private javax.swing.JLabel lb_salahNama;
    private javax.swing.JLabel lb_salahSandi;
    private javax.swing.JPanel panel_email;
    private javax.swing.JPanel panel_nama;
    private javax.swing.JPanel panel_sandi;
    private javax.swing.JTextField tf_email;
    private javax.swing.JPasswordField tf_konfirSandi;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JPasswordField tf_sandiBaru;
    // End of variables declaration//GEN-END:variables
}
