package main;

import java.awt.Dimension;
import java.awt.Rectangle;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utility.Koneksi_db;


// @author Putra Prasetya
public class Pegawai extends javax.swing.JFrame {
    private Connection conn = new Koneksi_db().connect();
    private DefaultTableModel tabmode;
    private String atr_nama;
    private String atr_telp;
    
    public Pegawai() {
        initComponents();       
    }
    
    public Pegawai(Rectangle bound) {
        initComponents();
        tabelPegawai();
        rb_pria.setSelected(true); 
        ta_alamat.setLineWrap(true);
        ta_alamat.setWrapStyleWord(true);
        
        // terima ukuran window & tetapkan di window yang aktif
        this.setBounds(bound);
               
        //saat restore dari kondisi maximize kembali ke ukuran minimal
        Dimension size = this.getSize();
        Double width = size.getWidth();
        Double height = size.getHeight();
        if (width > 1381 && height > 743) {
            this.setSize(800,500);
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bg21 = new utility.bg2();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_nama = new javax.swing.JTextField();
        tf_tmpt_lahir = new javax.swing.JTextField();
        rb_pria = new javax.swing.JRadioButton();
        rb_wanita = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        tf_no_telp = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_bersihkan = new javax.swing.JButton();
        tabelScrollPane = new javax.swing.JScrollPane();
        tbl_pegawai = new javax.swing.JTable();
        alamatScrollPane = new javax.swing.JScrollPane();
        ta_alamat = new javax.swing.JTextArea();
        date_tgl_lahir = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        btn_kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama");
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 14));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tempat Lahir");
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 14));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tanggal Lahir");
        jLabel3.setMaximumSize(new java.awt.Dimension(500, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(50, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 14));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Kelamin");
        jLabel4.setMaximumSize(new java.awt.Dimension(500, 14));
        jLabel4.setMinimumSize(new java.awt.Dimension(50, 14));
        jLabel4.setPreferredSize(new java.awt.Dimension(80, 14));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat");
        jLabel5.setPreferredSize(new java.awt.Dimension(80, 14));

        buttonGroup1.add(rb_pria);
        rb_pria.setForeground(new java.awt.Color(255, 255, 255));
        rb_pria.setText("Pria");

        buttonGroup1.add(rb_wanita);
        rb_wanita.setForeground(new java.awt.Color(255, 255, 255));
        rb_wanita.setText("Wanita");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No. Telepon");
        jLabel6.setPreferredSize(new java.awt.Dimension(80, 14));

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_bersihkan.setText("Bersihkan");
        btn_bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bersihkanActionPerformed(evt);
            }
        });

        tbl_pegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "No.Telepon", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_pegawai.getTableHeader().setReorderingAllowed(false);
        tbl_pegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pegawaiMouseClicked(evt);
            }
        });
        tabelScrollPane.setViewportView(tbl_pegawai);
        if (tbl_pegawai.getColumnModel().getColumnCount() > 0) {
            tbl_pegawai.getColumnModel().getColumn(1).setPreferredWidth(10);
        }

        ta_alamat.setColumns(20);
        ta_alamat.setRows(5);
        alamatScrollPane.setViewportView(ta_alamat);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Pegawai");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btn_kembali.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_kembali.setText("<< Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg21Layout = new javax.swing.GroupLayout(bg21);
        bg21.setLayout(bg21Layout);
        bg21Layout.setHorizontalGroup(
            bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg21Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nama)
                            .addComponent(tf_tmpt_lahir)
                            .addComponent(alamatScrollPane)
                            .addGroup(bg21Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(rb_pria)
                                .addGap(18, 18, 18)
                                .addComponent(rb_wanita))
                            .addComponent(tf_no_telp)
                            .addGroup(bg21Layout.createSequentialGroup()
                                .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bg21Layout.createSequentialGroup()
                                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_bersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(date_tgl_lahir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btn_kembali))
                .addGap(18, 18, 18)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addComponent(tabelScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                        .addGap(18, 18, 18))))
        );
        bg21Layout.setVerticalGroup(
            bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg21Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_tmpt_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(date_tgl_lahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rb_pria)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rb_wanita))
                        .addGap(11, 11, 11)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alamatScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_no_telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_simpan)
                            .addComponent(btn_ubah))
                        .addGap(13, 13, 13)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_bersihkan)
                            .addComponent(btn_hapus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_kembali))
                    .addComponent(tabelScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void tabelPegawai(){
        Object[] Baris = {"Nama", "No. Telepon", "Alamat"};
        tabmode = new DefaultTableModel(null, Baris);
        tbl_pegawai.setModel(tabmode);
        String query = "SELECT nama_peg, telp_peg, alamat_peg FROM pegawai";
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(query);
            while (hasil.next()){                
                String a = hasil.getString("nama_peg");                
                String b = hasil.getString("telp_peg");
                String c = hasil.getString("alamat_peg");
                String[] data={a,b,c};
                tabmode.addRow(data);
            }            
        } catch (SQLException e) {
            pesanSQLPopUp("Data tabel pegawai gagal ditampilkan",e);
        }
    } 
    
    private void pesanPopUp(String pesan){
        JOptionPane.showMessageDialog(null, pesan);
    }
    
    private void pesanSQLPopUp(String pesan, SQLException ee){
        JOptionPane.showMessageDialog(null, pesan+" : "+ee);
    }
    
    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        String nama = tf_nama.getText();
        String telp = tf_no_telp.getText();
        Date cast_tgl = (Date) date_tgl_lahir.getDate();
        if (nama.equals("")) pesanPopUp("Nama Kosong !. \nIsi terlebih dahulu.");
        else if (telp.equals("")) pesanPopUp("No. Telepon Kosong !. \nIsi terlebih dahulu.");
        else if (cast_tgl == null) pesanPopUp("Tanggal Kosong !.\nIsi terlebih dahulu.");
        else if (adaNamaTelp(nama,telp)) pesanPopUp("Nama dan No. Telepon Sudah Ada !");
        else {
            String query = "INSERT INTO pegawai VALUES (?,?,?,?,?,?,?)";
            try{
                PreparedStatement stat = conn.prepareStatement(query);
                stat.setString(1, null);
                stat.setString(2, nama);
                stat.setString(3, tf_tmpt_lahir.getText());
                
                SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd"); 
                String strDate = Date_Format.format(cast_tgl);
                stat.setString(4, strDate); 

                String jkel="";
                if(rb_pria.isSelected()) jkel="Pria";
                else jkel="Wanita";            
                stat.setString(5, jkel);
                stat.setString(6, ta_alamat.getText());
                stat.setString(7, telp);
                
                stat.executeUpdate();
                bersihkanMasukan();            
                tabelPegawai();
            } catch (SQLException e){
                pesanSQLPopUp("Data tidak bisa disimpan",e);
            }
        }             
    }//GEN-LAST:event_btn_simpanActionPerformed

    private boolean adaNamaTelp(String pnama, String ptelp){
        String query = "SELECT nama_peg FROM pegawai WHERE nama_peg = '"+pnama+"'";
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(query);
            if (hasil.next()){  // Jika nama ada                  
                query = "SELECT telp_peg FROM pegawai WHERE telp_peg = '"+ptelp+"'";
                hasil = stat.executeQuery(query);
                if (hasil.next()) return true; // Jika telp ada                    
            }
        } catch (SQLException e) {
            pesanSQLPopUp("Gagal cek nama telp",e);
        }
        return false;
    }       
    
    private void bersihkanMasukan(){
        tf_nama.setText("");
        tf_tmpt_lahir.setText("");
        date_tgl_lahir.setDate(null);
        rb_pria.setSelected(true);
        ta_alamat.setText("");
        tf_no_telp.setText("");
        tf_nama.requestFocus();
    }
    
    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        int id = ambilIdPeg();
        String nama = tf_nama.getText();
        String telp = tf_no_telp.getText();
        Date cast_tgl = (Date) date_tgl_lahir.getDate();
        if (nama.equals("")) pesanPopUp("Nama Kosong !. \nIsi terlebih dahulu");
        else if (telp.equals("")) pesanPopUp("No. Telepon Kosong !. \nIsi terlebih dahulu");
        else if (cast_tgl == null) pesanPopUp("Tanggal Kosong !. \nIsi terlebih dahulu");
        else if (adaNamaTelp(nama,telp)) pesanPopUp("Nama dan No. Telepon Sudah Ada !");
        else {
            String query = "UPDATE pegawai SET nama_peg=?, tmpt_lahir_peg=?, tgl_lahir_peg=?,"
                         + "jns_kel_peg=?, alamat_peg=?, telp_peg=? WHERE id_peg=?";
            try {                
                PreparedStatement stat = conn.prepareStatement(query);
                stat.setString(1, nama);
                stat.setString(2, tf_tmpt_lahir.getText());
                
                SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd"); 
                String strDate = Date_Format.format(cast_tgl);
                stat.setString(3, strDate);  

                String jkel="";
                if(rb_pria.isSelected()) jkel="Pria";
                else jkel="Wanita";
                stat.setString(4, jkel);
                stat.setString(5, ta_alamat.getText());
                stat.setString(6, telp);
                stat.setInt(7, id);

                stat.executeUpdate();
                bersihkanMasukan();            
                tabelPegawai();
            } catch (SQLException e){
                pesanSQLPopUp("Data gagal diubah",e);
            }
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void tbl_pegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pegawaiMouseClicked
        int bar = tbl_pegawai.getSelectedRow();
        String nama = tabmode.getValueAt(bar, 0).toString();
        String telp = tabmode.getValueAt(bar, 1).toString();
        this.atr_nama = nama;
        this.atr_telp = telp;
        String query = "SELECT * FROM pegawai WHERE nama_peg = '"+nama+"' AND telp_peg = '"+telp+"'";
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(query);            
            String a = "", b = "", d = "", e = "", f = "", g = "";            
            if (hasil.next()){
                a = hasil.getString("nama_peg");
                b = hasil.getString("tmpt_lahir_peg");
                Date c = hasil.getDate("tgl_lahir_peg");
                date_tgl_lahir.setDate(c);
                d = hasil.getString("jns_kel_peg");
                e = hasil.getString("alamat_peg");
                f = hasil.getString("telp_peg");                                
            }
            tf_nama.setText(a);
            tf_tmpt_lahir.setText(b);            
            switch (d) {
                case "Pria":
                    rb_pria.setSelected(true);
                    rb_wanita.setSelected(false);
                    break;
                case "Wanita":
                    rb_pria.setSelected(false);
                    rb_wanita.setSelected(true);
                    break;
                default:
                    rb_pria.setSelected(false);
                    rb_wanita.setSelected(false);
                    break;
            }
            ta_alamat.setText(e);
            tf_no_telp.setText(f);
        }catch(SQLException e){
            pesanSQLPopUp("Data dari tabel gagal diambil",e);
        }
    }//GEN-LAST:event_tbl_pegawaiMouseClicked
    
    private int ambilIdPeg(){
        String query = "SELECT id_peg FROM pegawai WHERE nama_peg = '"+atr_nama+"' AND telp_peg = '"+atr_telp+"'";
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(query);
            if (hasil.next()) return hasil.getInt("id_peg");            
        } catch (SQLException e){
            pesanSQLPopUp("Gagal ambil id pegawai",e);
        }
        return 0;
    }
    
    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        Rectangle bound = this.getBounds();
        new Menu(bound).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        int id = ambilIdPeg();
        int ok = JOptionPane.showConfirmDialog(null,"Hapus","Konfirmasi Dialog", 
                 JOptionPane.YES_NO_OPTION);
        if (ok==0){
            String query = "DELETE FROM pegawai WHERE id_peg='"+id+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(query);
                stat.executeUpdate();
                bersihkanMasukan();                
                tabelPegawai();                
            } catch (SQLException e){
                pesanSQLPopUp("Data gagal dihapus",e);
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_bersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bersihkanActionPerformed
        bersihkanMasukan();
    }//GEN-LAST:event_btn_bersihkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Pegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane alamatScrollPane;
    private utility.bg2 bg21;
    private javax.swing.JButton btn_bersihkan;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser date_tgl_lahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton rb_pria;
    private javax.swing.JRadioButton rb_wanita;
    private javax.swing.JTextArea ta_alamat;
    private javax.swing.JScrollPane tabelScrollPane;
    private javax.swing.JTable tbl_pegawai;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_no_telp;
    private javax.swing.JTextField tf_tmpt_lahir;
    // End of variables declaration//GEN-END:variables
}
